/* automatically generated by rust-bindgen 0.70.1 */

pub type __u64 = ::core::ffi::c_ulonglong;
pub type __u32 = ::core::ffi::c_uint;
pub type __u16 = ::core::ffi::c_ushort;
pub type u16_ = __u16;
pub type __be16 = __u16;
pub type __be32 = __u32;
pub type __kernel_pid_t = ::core::ffi::c_int;
pub type pid_t = __kernel_pid_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct task_struct {
    pub flags: ::core::ffi::c_uint,
    pub pid: pid_t,
    pub tgid: pid_t,
    pub comm: [::core::ffi::c_uchar; 16usize],
    pub real_parent: *mut task_struct,
    pub group_leader: *mut task_struct,
    pub mm: *mut mm_struct,
}
extern "C" {
    pub fn shim_task_struct_flags(task_struct: *mut task_struct) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_task_struct_flags_user(task_struct: *mut task_struct) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_task_struct_flags_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_pid(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_pid_user(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_pid_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_tgid(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_tgid_user(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_tgid_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_comm(task_struct: *mut task_struct) -> *mut ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_task_struct_comm_user(task_struct: *mut task_struct) -> *mut ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_task_struct_comm_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_real_parent(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_real_parent_user(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_real_parent_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_group_leader(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_group_leader_user(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_group_leader_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_mm(task_struct: *mut task_struct) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_task_struct_mm_user(task_struct: *mut task_struct) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_task_struct_mm_exists(task_struct: *mut task_struct) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mm_struct {
    pub arg_start: ::core::ffi::c_ulong,
    pub arg_end: ::core::ffi::c_ulong,
    pub exe_file: *mut file,
}
extern "C" {
    pub fn shim_mm_struct_arg_start(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_start_user(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_start_exists(mm_struct: *mut mm_struct) -> bool;
}
extern "C" {
    pub fn shim_mm_struct_arg_end(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_end_user(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_end_exists(mm_struct: *mut mm_struct) -> bool;
}
extern "C" {
    pub fn shim_mm_struct_exe_file(mm_struct: *mut mm_struct) -> *mut file;
}
extern "C" {
    pub fn shim_mm_struct_exe_file_user(mm_struct: *mut mm_struct) -> *mut file;
}
extern "C" {
    pub fn shim_mm_struct_exe_file_exists(mm_struct: *mut mm_struct) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct super_block {
    pub s_dev: ::core::ffi::c_ulong,
    pub s_root: *mut dentry,
}
extern "C" {
    pub fn shim_super_block_s_dev(super_block: *mut super_block) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_super_block_s_dev_user(super_block: *mut super_block) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_super_block_s_dev_exists(super_block: *mut super_block) -> bool;
}
extern "C" {
    pub fn shim_super_block_s_root(super_block: *mut super_block) -> *mut dentry;
}
extern "C" {
    pub fn shim_super_block_s_root_user(super_block: *mut super_block) -> *mut dentry;
}
extern "C" {
    pub fn shim_super_block_s_root_exists(super_block: *mut super_block) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inode {
    pub i_ino: ::core::ffi::c_ulong,
    pub i_mode: u16_,
    pub i_sb: *mut super_block,
}
extern "C" {
    pub fn shim_inode_i_ino(inode: *mut inode) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_inode_i_ino_user(inode: *mut inode) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_inode_i_ino_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_mode(inode: *mut inode) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_inode_i_mode_user(inode: *mut inode) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_inode_i_mode_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_sb(inode: *mut inode) -> *mut super_block;
}
extern "C" {
    pub fn shim_inode_i_sb_user(inode: *mut inode) -> *mut super_block;
}
extern "C" {
    pub fn shim_inode_i_sb_exists(inode: *mut inode) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qstr {
    pub hash_len: __u64,
    pub name: *const ::core::ffi::c_uchar,
}
extern "C" {
    pub fn shim_qstr_name(qstr: *mut qstr) -> *const ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_qstr_name_user(qstr: *mut qstr) -> *const ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_qstr_name_exists(qstr: *mut qstr) -> bool;
}
extern "C" {
    pub fn shim_qstr_hash_len(qstr: *mut qstr) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_qstr_hash_len_user(qstr: *mut qstr) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_qstr_hash_len_exists(qstr: *mut qstr) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dentry {
    pub d_flags: ::core::ffi::c_uint,
    pub d_parent: *mut dentry,
    pub d_name: qstr,
    pub d_sb: *mut super_block,
    pub d_inode: *mut inode,
}
extern "C" {
    pub fn shim_dentry_d_flags(dentry: *mut dentry) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_dentry_d_flags_user(dentry: *mut dentry) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_dentry_d_flags_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_parent(dentry: *mut dentry) -> *mut dentry;
}
extern "C" {
    pub fn shim_dentry_d_parent_user(dentry: *mut dentry) -> *mut dentry;
}
extern "C" {
    pub fn shim_dentry_d_parent_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_name(dentry: *mut dentry) -> *mut qstr;
}
extern "C" {
    pub fn shim_dentry_d_name_user(dentry: *mut dentry) -> *mut qstr;
}
extern "C" {
    pub fn shim_dentry_d_name_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_sb(dentry: *mut dentry) -> *mut super_block;
}
extern "C" {
    pub fn shim_dentry_d_sb_user(dentry: *mut dentry) -> *mut super_block;
}
extern "C" {
    pub fn shim_dentry_d_sb_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_inode(dentry: *mut dentry) -> *mut inode;
}
extern "C" {
    pub fn shim_dentry_d_inode_user(dentry: *mut dentry) -> *mut inode;
}
extern "C" {
    pub fn shim_dentry_d_inode_exists(dentry: *mut dentry) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vfsmount {
    pub mnt_root: *mut dentry,
}
extern "C" {
    pub fn shim_vfsmount_mnt_root(vfsmount: *mut vfsmount) -> *mut dentry;
}
extern "C" {
    pub fn shim_vfsmount_mnt_root_user(vfsmount: *mut vfsmount) -> *mut dentry;
}
extern "C" {
    pub fn shim_vfsmount_mnt_root_exists(vfsmount: *mut vfsmount) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mount {
    pub mnt_parent: *mut mount,
    pub mnt_mountpoint: *mut dentry,
    pub mnt: vfsmount,
}
extern "C" {
    pub fn shim_mount_mnt_parent(mount: *mut mount) -> *mut mount;
}
extern "C" {
    pub fn shim_mount_mnt_parent_user(mount: *mut mount) -> *mut mount;
}
extern "C" {
    pub fn shim_mount_mnt_parent_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint(mount: *mut mount) -> *mut dentry;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint_user(mount: *mut mount) -> *mut dentry;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_mnt(mount: *mut mount) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_mount_mnt_user(mount: *mut mount) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_mount_mnt_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_from_vfsmount(vfs: *mut vfsmount) -> *mut mount;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct path {
    pub mnt: *mut vfsmount,
    pub dentry: *mut dentry,
}
extern "C" {
    pub fn shim_path_mnt(path: *mut path) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_path_mnt_user(path: *mut path) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_path_mnt_exists(path: *mut path) -> bool;
}
extern "C" {
    pub fn shim_path_dentry(path: *mut path) -> *mut dentry;
}
extern "C" {
    pub fn shim_path_dentry_user(path: *mut path) -> *mut dentry;
}
extern "C" {
    pub fn shim_path_dentry_exists(path: *mut path) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct file {
    pub f_path: path,
    pub f_inode: *mut inode,
    pub f_flags: ::core::ffi::c_uint,
}
extern "C" {
    pub fn shim_file_f_path(file: *mut file) -> *mut path;
}
extern "C" {
    pub fn shim_file_f_path_user(file: *mut file) -> *mut path;
}
extern "C" {
    pub fn shim_file_f_path_exists(file: *mut file) -> bool;
}
extern "C" {
    pub fn shim_file_f_inode(file: *mut file) -> *mut inode;
}
extern "C" {
    pub fn shim_file_f_inode_user(file: *mut file) -> *mut inode;
}
extern "C" {
    pub fn shim_file_f_inode_exists(file: *mut file) -> bool;
}
extern "C" {
    pub fn shim_file_f_flags(file: *mut file) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_file_f_flags_user(file: *mut file) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_file_f_flags_exists(file: *mut file) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct linux_binprm {
    pub file: *mut file,
}
extern "C" {
    pub fn shim_linux_binprm_file(linux_binprm: *mut linux_binprm) -> *mut file;
}
extern "C" {
    pub fn shim_linux_binprm_file_user(linux_binprm: *mut linux_binprm) -> *mut file;
}
extern "C" {
    pub fn shim_linux_binprm_file_exists(linux_binprm: *mut linux_binprm) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_family: ::core::ffi::c_ushort,
}
extern "C" {
    pub fn shim_sockaddr_sa_family(sockaddr: *mut sockaddr) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_sa_family_user(sockaddr: *mut sockaddr) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_sa_family_exists(sockaddr: *mut sockaddr) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_in {
    pub sin_family: ::core::ffi::c_ushort,
    pub sin_port: __be16,
    pub sin_addr: sockaddr_in__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_in__bindgen_ty_1 {
    pub s_addr: __be32,
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family_user(sockaddr_in: *mut sockaddr_in)
        -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family_exists(sockaddr_in: *mut sockaddr_in) -> bool;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port_user(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port_exists(sockaddr_in: *mut sockaddr_in) -> bool;
}
extern "C" {
    pub fn shim_sockaddr_in_s_addr(sa: *mut sockaddr_in) -> __be32;
}
extern "C" {
    pub fn shim_sockaddr_in_s_addr_exists(sa: *mut sockaddr_in) -> bool;
}
